name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    strategy:
      matrix:
        directory: [dev]

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Configure AWS Credentials from AWS Account
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::730335281548:role/k8s-iam-oidc-role
      #     aws-region: us-east-1
      #     role-session-name: k8s-iam-role-deployment

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init ${{ matrix.directory }}
        working-directory: deploys/${{ matrix.directory }}
        run: terraform init

      - name: Terraform Plan ${{ matrix.directory }}
        working-directory: deploys/${{ matrix.directory }}
        run: terraform plan
