name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: deploys/dev
        run: terraform init

      - name: Terraform Format
        working-directory: deploys/dev
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: deploys/dev
        run: terraform plan
